const data = {
  products: [
    {
      _id: '1',
      name: 'Attack 1',
      slug: 'Attack 1',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Trojan horse attacks',
    },
    {
      _id: '2',
      name: 'Attack 2',
      slug: 'Attack 2',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Denial of service attack',
    },
    {
      _id: '3',
      name: 'Attack 3',
      slug: 'Attack 3',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Hackers',
    },
    {
      _id: '4',
      name: 'Attack 4',
      slug: 'Attack 4',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Virus',
    },
  ],
};
export default data;
